### ISSUE TITLE
Custom Object Name Links Don't Work

### ISSUE THREAD

**Issue by SRosewood** [tprouvot/Salesforce-Inspector-reloaded#218] opened 2023-11-10 09:54 UTC
**Make sure to read the troubleshooting section before creating an issue**

**Describe the bug**
When clicking an object name via SF inspector, this should take the user to the object manager page for that object in setup. Instead the url object name is undefined and navigates the user to the object manager home page in setup.

This works for standard objects but not custom objects.

**To Reproduce**
1 - Open an org
2 - Open SF Inspector
3 - Search for a custom object
4 - Click Object Name (URL Link)

**Expected behavior**
Should take user to custom object manager page for that object.

**Screenshots**
![1 - Click Custom Object](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/83288247/48653282-61e0-48d7-b24b-4fdf1bba814d)
![2 - Undefined URL](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/83288247/bea38e15-266c-488a-a2ce-4eb0900bfaa1)
<img width="1276" alt="3 - Object Manager Home" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/83288247/954533c2-1a7d-414d-bce7-eae97552f407">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Browser: Chrome
 - Version: 119.0.6045.123

**Comment by tprouvot** [comment] 2023-11-10 13:30
Hi @SimonKaya ,
Could you run the query 
`SELECT COUNT() FROM EntityDefinition` and tell me how many records are returned.

I don't know how are you dev skills but you may check if everything is going fine during the retrieve of the EntityDefinition objects.

![2023-11-10_14-24-24 (1)](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/0f9e4236-7172-4e8c-85e2-77779488e2b4)

If you could share me the results via a video or gif it could be great, if not we can see if we can schedule a short meeting

**Comment by SimonKaya** [comment] 2023-11-13 09:22
Thanks for the fast response @tprouvot 

I don't use the chrome inspector or debugging tool for my line of work but think I've caught what you were looking for. I seemed to have to refresh the tab to catch the debug however now sure if that makes a difference or not based on your video.

Looks like my count is 2620.

https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/83288247/a35dda0d-53e0-4ec1-af2f-b9a47634ec2a

If you need more information or example it might be easier to plan a call at.

**Comment by tprouvot** [comment] 2023-11-13 09:52
@SimonKaya 
Great thanks for this 👏 
If the total number of EntityDefinition is 2620 it means you should iterate only two times in this loop.
Could you check if the object you are looking for is contained in this list ? 

To be able to do that you'll have to put a conditional breakpoint by testing the record.QualifiedApiName with your custom object

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/6f7b9a28-f508-41ac-bef0-3d48f941ec5f)

**Comment by SRosewood** [comment] 2023-11-13 20:50
@tprouvot 

The expected record looks to be there from what I can see:
<img width="1440" alt="Configuration Item Debug" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/83288247/f35c8295-fd12-4d12-bad3-8e2606e228f6">

**Comment by jefersonchaves** [comment] 2023-11-16 12:44
The potential cause is due to the following [code](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/addon/popup.js#L1196-L1209) where it expects `durableId` that is undefined:
<img width="1169" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/1755734/85c887fa-a8e2-49f4-8e86-2dabbfbf0605">

In my troubleshooting it seems to be caused by `durableId` not being retrieved at [first describe](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/addon/popup.js#L431), later the `durableId` it is retrieved at via this [line](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/addon/popup.js#L438C7-L438C27) but the [addEntity code](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/addon/popup.js#L438C7-L438C27) does not check if the entity previously had no `durableId`.

So, a potentially fix is to add this check.

**Comment by jefersonchaves** [comment] 2023-11-16 12:49
@tprouvot - I have created #228 based on what I understood, hopefully it helps.

**Comment by tprouvot** [comment] 2023-11-16 13:30
Hi @SRosewood ,
Could you check if the fix of @jefersonchaves could resolve your issue ?
To do so, you can create a conditional breakpoint (based on the name of your custom object) on addEntity method from popup.js file and enter this code in the dev console `entity.durableId = durableId;`

After that check if the link in the popup is functional

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/534e5e2d-51c2-4f38-8815-428fcbcd8521)

**Comment by jefersonchaves** [comment] 2023-11-16 15:16
Yes, I did the test manually on my browser before the PR. That is the same code and it fixed the issue.

**Comment by tprouvot** [comment] 2023-11-20 10:43
I'm closing the issue since Jeferson provided a fix, please feel free to reopen it if you're issue is still running

**Closed by tprouvot** 2023-11-20 10:43 UTC
Labels: bug

**Comment by SRosewood** [comment] 2023-11-20 18:52
Sorry for the delayed response @tprouvot .

Yes has worked thanks @jefersonchaves look forward to the fix making a release soon. 👍
