### ISSUE TITLE
Request for Enhancement: Formatting and Commenting Features for SOQL Queries

### ISSUE THREAD

**Issue by santaji1986** [tprouvot/Salesforce-Inspector-reloaded#289] opened 2024-01-25 21:31 UTC
I am encountering challenges when working with lengthy SOQL queries that involve multiple select fields and subqueries. These queries are often copied from batch jobs or generated for analyzing various issues.

It would be highly beneficial if the [Salesforce-Inspector-reloaded](https://github.com/tprouvot/Salesforce-Inspector-reloaded) could support the formatting of SOQL queries, allowing for proper indentation and the ability to include comments. For example:

``` SQL
SELECT column1, column2
FROM table1
WHERE condition1
    AND condition2
    OR condition3
// This is a comment using double slashes
```

Enabling comments using any of the common styles such as `//`, `/**/`, `--`, or `;;` would enhance the experience, especially when dealing with long nested queries for data analysis.

**Comment by dufoli** [comment] 2024-03-19 13:45
duplicate of #216 and #359

**Comment by tprouvot** [comment] 2024-03-19 13:51
@santaji1986 I'll close this and the follow up will be done in the #359

**Closed by tprouvot** 2024-03-19 13:51 UTC
Labels: enhancement
