### ISSUE TITLE
Opening A 2nd Menu Closes The 1st

### ISSUE THREAD

**Issue by RebbePod** [tprouvot/Salesforce-Inspector-reloaded#212] opened 2023-11-08 21:01 UTC
**Is your feature request related to a problem? Please describe.**
When on the show all data screen using the dropdown menu at the end of one field to say export related records, even after clicking on export it won't close the menu. When selecting a different field it also doesn't hide the first field causing them to at times overlap

**Describe the solution you'd like**
have it hide after an option is clicked or another menu is selected

**Describe alternatives you've considered**
going to sleep

**Comment by tprouvot** [comment] 2023-11-09 08:03
Hi @RebbePod ,

Your request seems to be a duplicate of this one #159.
As this one comes after, I'll close it but you can subscribe to the first one to check for updates.

**Closed by tprouvot** 2023-11-09 08:03 UTC
Labels: enhancement

**Comment by RebbePod** [comment] 2023-11-09 15:23
Thank you, I actually looked to see if existed. :)
See my comment there
