### ISSUE TITLE
[data-export] Browser crash on Export

### ISSUE THREAD

**Issue by patriciaxa** [tprouvot/Salesforce-Inspector-reloaded#350] opened 2024-03-13 16:48 UTC
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
Browser closes when clicking on the 'Copy...' buttons in the 'Export result' section.

**To Reproduce**
1. Go to 'https://visa-gateway.my.salesforce.com/console' or https://visa-gateway.lightning.force.com/ and login. Go to section 'Reports'.
2. Click on the arrow that displays the SF Inspector tools and click on 'Data Export'.
3. Complete the requested query, in my case, the data in contained in "AgentWork" and "LivechatTranscript", and click on button 'Run Export'.
4. You will get the results. Then click on the buttons of "Export result", such as 'Copy (Excel format)', 'Copy (CSV)' or 'Copy (JSON)' and then all the windows of the browser will close suddenly without saving any data in the clipboard to paste.

**Expected behavior**
When clicking on the buttons from "Export result", such as 'Export (Excel format)', 'Copy (CSV)' or 'Copy (JSON)', the data must be copied and the browser must not close. It should be able to copy the data and be ready to paste in an Excel sheet, for example.

**Screenshots**
I attach screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise version 22H2
 - Browser: Chrome and Edge (same issue in both)
 - Version: Chrome 122.0.6261.128 (Build oficial) (64 bits); Edge for Business 122.0.2365.80 (Compilación oficial) (64 bits)

**Additional context**
This issue started to occure this month, March 2024. Previously I did not face any issues.
![step click on export](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/163330865/7831a01b-8071-490f-a58d-ce9089ab611b)
![step open sf inspector](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/163330865/0596ebeb-94bc-4984-8bdd-aad3633eecf5)

**Comment by tprouvot** [comment] 2024-03-13 17:16
Hi @patriciaxa,
We could experiment browser crash with very large export but exporting 6k records should definitely not.

As [mentioned ](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/331#issuecomment-1978846149) in a previous issue, could you check the same request on the same org with another computer ? 
Also could you check with one another admin if he's facing the same issue from his computer ?
Thanks

**Comment by patriciaxa** [comment] 2024-03-13 19:08
Hi! We had tested with a different user in a different computer and he faced the same issue. I used to download around 35.000 records monthly in each query and had never had issues... I don't have any other users outside the company to ask for extra testing....

**Comment by tprouvot** [comment] 2024-03-14 13:46
Does this happen on other objects like Account or Contact ?

**Comment by patriciaxa** [comment] 2024-03-14 14:01
No, Account and Contact work fine.

**Comment by TejaDomala97** [comment] 2024-03-15 15:04
Hello,

Hope you're doing good!

I was searching if anyone have already raised a ticket for this issue and I found this today.

Even I've been facing the same issue since few days and I've tried it in different devices and different browsers as well.
I am able to download/copy with 500 results, however, when I try for 10000 or more, browser was crashing.

**Comment by tprouvot** [comment] 2024-03-15 15:35
Hi @TejaDomala97,
Would you mind testing the export with all your other browser extensions disabled ? 
Just to eliminate this root cause

**Comment by tprouvot** [comment] 2024-03-15 15:50
Hi @patriciaxa,
Would you mind scheduling a gmeet in order to be able to debug the issue on your commuter ?
You can reach me on my [Linkedin profile](https://www.linkedin.com/in/thomasprouvot/)

**Comment by tprouvot** [comment] 2024-03-21 07:50
Hi @patriciaxa @TejaDomala97 
As I did not get any answer I'll close this issue, I can re-open it later if you provide some details.

**Comment by TejaDomala97** [comment] 2024-04-01 08:59
Hello @tprouvot,

Apologies for no response. Was occupied in another priority task.

I've disabled all the other extensions and tried running the Export in the inspector reloaded tool. However, it still is giving the same issue - entire browser is crashed when clicked on either of the copy options.

I've seen lot of other folk facing the same issue as well.

Please let me know if any more information is needed!

**Comment by tprouvot** [comment] 2024-04-02 13:24
Hi @TejaDomala97 
You can reach me on Linkedin, we'll try to schedule a meeting to investigate live

**Comment by TejaDomala97** [comment] 2024-04-23 07:42
Hey @tprouvot,

Apologies again, for long delayed response.

Sure, will reach you out on LinkedIn today!

**Comment by gjmonterde** [comment] 2024-05-03 20:36
Hello! We are also experiencing the same issue. Hope there’s an update.

**Closed** 2024-07-05 13:21 UTC
Labels: bug
