### ISSUE TITLE
Extention does not work with new XXX.salesforce-setup.com domain

### ISSUE THREAD

**Issue by bacasystems-IT** [tprouvot/Salesforce-Inspector-reloaded#392] opened 2024-04-17 19:13 UTC
**Describe the bug**
Salesforce started rolling out the new setup domain and the chrome extension doesn't show in setup pages for orgs with the new domain.

**To Reproduce**
1. Log into org with new setup domain
2. observe side pannel shows in normal SF
3. go into setup
4. observe it does not load

**Expected behavior**
extension to work in orgs with .salesforce-setup.com setup domains
**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/41757560/a8480cf4-56d6-4041-a6ca-9293dbb02af7)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version Version 123.0.6312.59 (Official Build) (64-bit)

**Additional context**
(https://help.salesforce.com/s/articleView?id=release-notes.rn_general_allow_setup_domain.htm&language=en_US&release=248&type=5)

**Comment by TimPaulaskasDS** [comment] 2024-04-17 20:26
I am having this issue as well. It appears that when you go to Setup it now uses -setup in the domain name salesforce-setup.com.

**Comment by tprouvot** [comment] 2024-04-17 22:19
Hi @bacasystems-IT, 
I'm closing this issue since it's a duplicate of #389, already discussed and fixed

**Closed** 2024-04-17 22:20 UTC
Labels: bug
