### ISSUE TITLE
Inspector tab not loading on sandbox setup pages

### ISSUE THREAD

**Issue by shnrz** [tprouvot/Salesforce-Inspector-reloaded#393] opened 2024-04-17 23:52 UTC
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**
The Inspector tab is not loading anymore for any Setup lightning page on sandboxes. This started happening when the sandbox's URL structure for lightning setup pages changed to: https://ExampleDomainName.sandbox.my.salesforce-setup.com/lightning/setup/

**To Reproduce**
1. Log into a sandbox.
2. Click the gear icon on the top right.
3. Click Setup.
4. See the setup home page where the SF Inspector Reloaded blue tab is not loading onto the page.

**Expected behavior**
Normal behavior is that the Setup home page loads and includes the Salesforce Inspector Reloaded blue tab on the side of the page.

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/9031954/e36be563-cc76-4922-b2e8-f6e79ce4a730)

**Desktop (please complete the following information):**
 - OS: Windows 10 (version 22H2 OS Build 19045.4291)
 - Browser: Edge (version 123.0.2420.97)
 - Salesforce Inspector Reloaded extension version: 1.22

**Additional context**
It's possible that the extension manifest needs to be updated to include the new URL for sandbox setup pages.

**Comment by tprouvot** [comment] 2024-04-18 05:34
Hi @shnrz,

I'm closing this request since it's a duplicate of the #389. 
Should be available today or tomorrow in the beta version

**Closed** 2024-04-18 05:34 UTC
Labels: bug
